version: '3'
services:

  # Starts the P/S emulator
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
    ports:
      - "8085:8085"
    entrypoint: gcloud beta emulators pubsub start --project test-project --host-port 0.0.0.0:8085
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pubsub:8085"]
      interval: 5s
      timeout: 10s
      retries: 3

  infra-builder-image:
    image: censys-infra-builder:local
    build:
      context: .
      dockerfile: ./infra/builder/Dockerfile

  # same logic can be applied for a common runtime image.

  # Runs the "scanner"
  scanner:
    depends_on:
      pubsub:
        condition: service_healthy
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_PROJECT_ID: test-project
    build:
      context: .
      dockerfile: ./cmd/scanner/Dockerfile

  # Runs the "processor"
  processor:
    depends_on:
      pubsub:
        condition: service_healthy
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_PROJECT_ID: test-project
    build:
      context: .
      dockerfile: ./cmd/processor/Dockerfile
